Resources:
  GoodExample:
    Type: AWS::EFS::FileSystem
    Properties:
      AvailabilityZoneName: "String"
      BackupPolicy:
        Status: "String"
      BypassPolicyLockoutSafetyCheck: false
      Encrypted: false
      FileSystemPolicy: JSON
      FileSystemTags: FileSystemTags
      KmsKeyId: "String"
      LifecyclePolicies: LifecyclePolicies
      PerformanceMode: "String"
      ProvisionedThroughputInMibps: Number
      ThroughputMode: "String"
