Resources:
  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: "String"
      EnableKeyRotation: false
      Enabled: false
      KeyPolicy: JSON # Required
      KeySpec: "String"
      KeyUsage: "String"
      MultiRegion: false
      PendingWindowInDays: Number
      Tags: Tags
