Resources:
  GoodInstance:
    Type: AWS::EC2::Instance
    Properties:
      AdditionalInfo: "String"
      Affinity: "String"
      AvailabilityZone: "String"
      BlockDeviceMappings: BlockDeviceMappings
      CpuOptions:
        CoreCount: Number
        ThreadsPerCore: Number
      CreditSpecification:
        CPUCredits: "Number"
      DisableApiTermination: false
      EbsOptimized: false
      ElasticGpuSpecifications: ElasticGpuSpecifications
      ElasticInferenceAccelerators: ElasticInferenceAccelerators
      EnclaveOptions:
        Enabled: false
      HibernationOptions:
        Configured: false
      HostId: "String"
      HostResourceGroupArn: "String"
      IamInstanceProfile: "String"
      ImageId: "String"
      InstanceInitiatedShutdownBehavior: "String"
      InstanceType: "String"
      Ipv6AddressCount: Number
      Ipv6Addresses: Ipv6Addresses
      KernelId: "String"
      KeyName: "String"
      LaunchTemplate:
        LaunchTemplateId: "String"
        LaunchTemplateName: "String"
        Version: "String"
      LicenseSpecifications: LicenseSpecifications
      Monitoring: String
      NetworkInterfaces: NetworkInterfaces
      PlacementGroupName: "String"
      PrivateIpAddress: "String"
      RamdiskId: "String"
      SecurityGroupIds: SecurityGroupIds
      SecurityGroups: SecurityGroups
      SourceDestCheck: false
      SsmAssociations: SsmAssociations
      SubnetId: "String"
      Tags: Tags
      Tenancy: "String"
      UserData: "String"
      Volumes: Volumes
