Resources:
  GoodRepository:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: "String"
        KmsKey: "String"
      ImageScanningConfiguration:
        ScanOnPush: String
      ImageTagMutability: "String"
      LifecyclePolicy:
        LifecyclePolicyText: "String"
        RegistryId: "String"
      RepositoryName: "String"
      RepositoryPolicyText: JSON
      Tags: Tags
