Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri: "String"
        S3Bucket: "String"
        S3Key: "String"
        S3ObjectVersion: "String"
        ZipFile: "String"
      CodeSigningConfigArn: "String"
      DeadLetterConfig:
        TargetArn: "String"
      Description: "String"
      Environment:
      FileSystemConfigs: FileSystemConfigs
      FunctionName: "String"
      Handler: "String"
      ImageConfig:
        Command:
          -
        EntryPoint:
          -
        WorkingDirectory: "String"
      KmsKeyArn: "String"
      Layers: Layers
      MemorySize: Number
      PackageType: "String"
      ReservedConcurrentExecutions: Number
      Role: "String" # Required
      Runtime: "String"
      Tags: Tags
      Timeout: Number
      TracingConfig:
        Mode: "String"
      VpcConfig:
        SecurityGroupIds:
          -
        SubnetIds:
          -
